name: Kafka Project CI

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
          # Checks out the repository code
      - name: Git Clone Repository
        uses: actions/checkout@v4

      # Sets up Python environment
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      # Install project dependencies
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      # Run linting
      - name: Run Linter
        run: |
          # Run flake8 to check for style issues
          flake8 .

      # Run unit tests
      - name: Run Unit Tests
        run: |
          pytest .

      # lint terraform codes
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7

      - name: Terraform Format Check
        run: |
          cd terraform
          terraform fmt -check

      - name: Terraform Validate
        run: |
          cd terraform
          terraform init
          terraform validate
          
  build:
    needs: test                       # Ensures build only happens after tests pass
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Build Docker Images
        run: |
          # docker build -t producer ./producer
          # docker build -t consumer ./consumer
          docker build -t kafka-project .

      
      # - name: Push to ECR
      #   env:
      #     AWS_REGION: us-east-1
      #   run: |
      #     aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin ${{ secrets.ECR_REGISTRY }}
      #     docker push ${{ secrets.ECR_REGISTRY }}/producer
      #     docker push ${{ secrets.ECR_REGISTRY }}/consumer

      #  Push to Docker Hub
      # - name: Push to Docker Hub
      #   env:
      #     DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      #     DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      #   run: |
      #     docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      #     docker push your-dockerhub-username/kafka-project


  # deploy:
  #   needs: build
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
      
  #     - name: Configure AWS Credentials
  #       uses: aws-actions/configure-aws-credentials@v4
  #       with:
  #         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  #         aws-region: us-east-1

  #     - name: Deploy to ECS
  #       run: |
  #         aws ecs update-service --cluster kafka-cluster --service producer-service --force-new-deployment
  #         aws ecs update-service --cluster kafka-cluster --service consumer-service --force-new-deployment










































# name: Terraform Infrastructure CI

# on:
#   push:
#     branches: [ main ]
#     paths:
#       - 'terraform/**'

# jobs:
#   terraform-validate:
#     runs-on: ubuntu-latest
    
#     steps:
#       - name: Checkout Repository
#         uses: actions/checkout@v4

#       - name: Setup Terraform
#         uses: hashicorp/setup-terraform@v3
#         with:
#           terraform_version: 1.5.7

#       - name: Terraform Format Check
#         run: |
#           cd terraform
#           terraform fmt -check

#       - name: Terraform Validate
#         run: |
#           cd terraform
#           terraform init
#           terraform validate

#       - name: Terraform Plan
#         env:
#           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
#           AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
#         run: |
#           cd terraform
#           terraform plan